/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: "none",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/(.*)$",
    "^@/env(.*)$",
    "^@/actions(.*)$",
    "^@/app/(.*)$",
    "^@/components/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/config/(.*)$",
    "^@/data(.*)$",
    "^@/hooks/(.*)$",
    "^@/lib/(.*)$",
    "^@/schemas(.*)$",
    "^@/styles/(.*)$",
    "^@/types/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
};
